### PR TITLE
Update installation instructions

### PR DESCRIPTION
**Pull request by verythorough**
For greater simplicity and consistency with Netlify users’ existing configuration files, we’re deprecating experimental support for Netlify config files in YAML or JSON (https://github.com/netlify/build/issues/975).

To get new plugin users started on the right foot, I’m proposing updates for all plugin READMEs to use `netlify.toml` format in the installation instructions.

**This docs-only change should require no updates to your plugin code.**

I've also made the following updates to reflect the current plugins API:
- Replaced `type` with `package`.
- Removed the `npm install` step. This is no longer necessary.

### CODE REVIEW

**Comment by neverendingqs** [comment]
Thanks. YAML seems pretty common across different services (CircleCI, Travis CI, Serverless, CloudFormation) and arguably more readable than toml.

Where can I find out more about why toml was chosen as the config format?

@verythorough

**Comment by verythorough** [comment]
Hi @neverendingqs! Some of the information is in the linked issue: https://github.com/netlify/build/issues/975

The TOML format has been used for Netlify configuration files [since 2016](https://www.netlify.com/blog/2016/08/30/introducing-deploy-contexts-in-netlify/#introducing-the-netlify-toml-file). It's the only format currently supported (and documented) across the entire platform. Last October, we added experimental support for YAML and JSON formats, but found that providing multiple formats added unneeded complexity and user frustration as folks struggled to convert their existing `netlify.toml` files to work with `netlify.yml`-formatted plugins instructions.

YAML is definitely popular, and many folks (including myself) are not particular fans of TOML. There's a chance that we will add YAML support again sometime in the future. If we do, we'll plan for more comprehensive support, with full compatibility and multi-format documentation. We don't have the bandwidth to do that now, though.

**Comment by verythorough** [comment]
@neverendingqs any follow-up on this PR?

We're now displaying plugins in the Netlify UI, using the list at https://github.com/netlify/plugins/blob/master/plugins.json. In order to ensure that all plugins in the UI are functional and match the documented configuration methods, I'll be making a PR tomorrow to remove this plugin.

We'll be happy to add it back when this PR is merged and you can confirm that the plugin still works in the Netlify Build Plugins Beta!

**Comment by neverendingqs** [comment]
Sorry for the delay. Thanks for updating the docs!

**Comment by verythorough** [comment]
Awesome, thanks for building this plugin!

**Pull request merged**
